 [tool.poetry]
name = "tsp"
version = "0.1.0"
description = ""
authors = ["stormynight9 <ferjani.nader@hotmail.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
